name: Build and push container images

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-images:
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v5

      - uses: https://data.forgejo.org/docker/setup-buildx-action@v3

      - name: Login to code.forgejo.org
        uses: https://data.forgejo.org/docker/login-action@v3
        with:
          registry: code.forgejo.org
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.CODEBERG_TOKEN }}

      - name: Login to ghcr.io
        uses: https://data.forgejo.org/docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to git.erwanleboucher.dev
        uses: https://data.forgejo.org/docker/login-action@v3
        with:
          registry: git.erwanleboucher.dev
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.OWNER_TOKEN }}

      - name: Compute image metadata
        id: meta
        uses: https://data.forgejo.org/docker/metadata-action@v5
        with:
          images: |
            code.forgejo.org/${{ vars.USERNAME }}/runner
            ghcr.io/${{ vars.USERNAME }}/runner
            git.erwanleboucher.dev/${{ vars.USERNAME }}/runner
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        uses: https://data.forgejo.org/docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
